apiVersion: v1
kind: ServiceAccount
metadata:
  # This matches the target resource your SecretStore looks for
  name: {{ include "multi-tenant-app.fullname" . }}-eso-sa
  namespace: {{ .Release.Namespace | default "default" }}
  annotations:
    # The magical EKS hook: links the K8s identity to the AWS IAM framework
    eks.amazonaws.com/role-arn: {{ .Values.eso.roleArn | quote }}
  labels:
    {{- include "multi-tenant-app.labels" . | nindent 4 }}